// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: miVpALEuuUaq61WfC71rVq
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : ("img.annoimage {\n    transition: transform 0.1s;\n}\n\nimg.annoimage:hover {\n    transform:scaleX(1.2), scaleY(1.2);\n}\n\n#navbar {\n  position: fixed; /* Make it stick/fixed */\n  top: -100px; /* Hide the navbar 50 px outside of the top view */\n  width: 100%; /* Full width */\n  transition: top 0.3s; /* Transition effect when sliding down (and up) */\n}\n\n::selection {\n  background: #7E00AD;\n  color: #ffffff;\n}\n\n.add-shadow{\n  border: #CACACA 0px 0px 1px 0px;\n}\n" as const)
      }
    >
      {children}
    </EmbedCss>
  );
}
