// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: miVpALEuuUaq61WfC71rVq
// Component: oJRzKe_Tkb
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: miVpALEuuUaq61WfC71rVq/projectcss
import sty from "./PlasmicButtonPink.module.css"; // plasmic-import: oJRzKe_Tkb/css

export type PlasmicButtonPink__VariantMembers = {};

export type PlasmicButtonPink__VariantsArgs = {};
type VariantPropType = keyof PlasmicButtonPink__VariantsArgs;
export const PlasmicButtonPink__VariantProps = new Array<VariantPropType>();

export type PlasmicButtonPink__ArgsType = {};
type ArgPropType = keyof PlasmicButtonPink__ArgsType;
export const PlasmicButtonPink__ArgProps = new Array<ArgPropType>();

export type PlasmicButtonPink__OverridesType = {
  root?: p.Flex<"div">;
  getACallBack?: p.Flex<"div">;
};

export interface DefaultButtonPinkProps {
  className?: string;
}

function PlasmicButtonPink__RenderFunc(props: {
  variants: PlasmicButtonPink__VariantsArgs;
  args: PlasmicButtonPink__ArgsType;
  overrides: PlasmicButtonPink__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"getACallBack"}
        data-plasmic-override={overrides.getACallBack}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.getACallBack
        )}
      >
        {"Get a quote"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "getACallBack"],
  getACallBack: ["getACallBack"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  getACallBack: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonPink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonPink__VariantsArgs;
    args?: PlasmicButtonPink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonPink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButtonPink__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButtonPink__ArgProps,
      internalVariantPropNames: PlasmicButtonPink__VariantProps
    });

    return PlasmicButtonPink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButtonPink";
  } else {
    func.displayName = `PlasmicButtonPink.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonPink = Object.assign(
  // Top-level PlasmicButtonPink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    getACallBack: makeNodeComponent("getACallBack"),

    // Metadata about props expected for PlasmicButtonPink
    internalVariantProps: PlasmicButtonPink__VariantProps,
    internalArgProps: PlasmicButtonPink__ArgProps
  }
);

export default PlasmicButtonPink;
/* prettier-ignore-end */
